# Generated by Django 5.0.4 on 2024-04-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["lastname", "firstname"], name="store_custo_lastnam_bcd537_idx"
            ),
        ),
    ]
