# Generated by Django 5.0.4 on 2024-04-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_address_zip_customer_store_custo_lastnam_bcd537_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customer", name="store_custo_lastnam_bcd537_idx",
        ),
        migrations.RenameField(
            model_name="customer", old_name="firstname", new_name="givenname",
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["lastname", "givenname"], name="store_custo_lastnam_317d3d_idx"
            ),
        ),
    ]
