# Generated by Django 5.0.4 on 2024-05-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_rename_price_product_unit_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection", options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(name="product", options={"ordering": ["title"]},),
        migrations.AlterField(
            model_name="product", name="description", field=models.TextField(null=True),
        ),
    ]
